### ISSUE TITLE
Would you kindly add the option for a logo to your mint-keywind-theme?

### ISSUE THREAD

**Issue by Alfagun74** [MitsuhaYuki/MitsuhaYuki#1]

**Comment by MitsuhaYuki** [comment]
I'm very sorry to have kept you waiting for so long, but the customizable logo feature has now been added to [mint-keywing-theme](https://github.com/MitsuhaYuki/mint-keywind-theme?tab=readme-ov-file#new-theme-keywind-mint-flavor). You can find the configurable options and corresponding explanations about the logo in [theme.properties](https://github.com/MitsuhaYuki/mint-keywind-theme/blob/main/theme/keywind-mint-flavor/login/theme.properties). For any further questions about this project, please mention to [mint-keywind-theme issues](https://github.com/MitsuhaYuki/mint-keywind-theme/issues) directly.

**Comment by Alfagun74** [comment]
tysm!
